import localFont from 'next/font/local';
import { Inter } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css';

// FONTS AND FONT-OPTIMIZATION
// --- primary font-family (Heading and Titles)
const inter = Inter({
  subsets: ['latin'],
});

// --- secondary font-family (Summary Briefs and Inlines)
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});

//  --- ternary-regular font-family (Inline Code Snippets)
const satoshiRegular = localFont({
  src: './fonts/Satoshi-Regular.woff',
  variable: '--font-satoshi-regular',
});

//  --- ternary-medium font-family (Inline Code Snippets)
const satoshiMedium = localFont({
  src: './fonts/Satoshi-Medium.woff',
  variable: '--font-satoshi-medium',
});

//  --- ternary-bold font-family (Inline Code Snippets)
const satoshiBold = localFont({
  src: './fonts/Satoshi-Bold.woff',
  variable: '--font-satoshi-bold',
});

// --- ternary-black font-family (Inline Code Snippets)
const satoshiBlack = localFont({
  src: './fonts/Satoshi-Black.woff',
  variable: '--font-satoshi-black',
});

// --- quadra-regular font-family (View-Page Titles and Headings)
const clashRegular = localFont({
  src: './fonts/ClashGrotesk-Regular.woff',
  variable: '--font-clash-regular',
});

//  --- quadra-medium font-family (View-Page Titles and Headings)
const clashMedium = localFont({
  src: './fonts/ClashGrotesk-Medium.woff',
  variable: '--font-clash-medium',
});

//  --- quadra-semibold font-family (View-Page Titles and Headings)
const clashSemiBold = localFont({
  src: './fonts/ClashGrotesk-Semibold.woff',
  variable: '--font-clash-semibold',
});

//  --- quadra-bold font-family (View-Page Titles and Headings)
const clashBold = localFont({
  src: './fonts/ClashGrotesk-Bold.woff',
  variable: '--font-clash-bold',
});

// --- Home Page Metadata Object (SEO and Ranking)
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// --- Main Root-Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} antialiased`}>
        {/* Children Component (App Component) */}
        {children}

        {/* --- Vercel Live Analytics-Tracker Component */}
        <Analytics />

        {/* --- Vercel Speed Insights Component */}
        <SpeedInsights />
      </body>
    </html>
  );
}
